"""Global data and common functions module. Also defines :class:`Heightmap` class."""

import moderngl as mgl
import bpy, bpy.types

import uuid, re

class Heightmap:
	"""A wrapper around ModernGL textures."""
	def __init__(self, name: str, txt: mgl.Texture):
		"""Constructor method.

		:param name: Display name of the stored texture.
		:type name: :class:`str`
		:param txt: Texture to wrap.
		:type txt: :class:`moderngl.Texture:`"""
		self.name = name
		self.texture = txt
	
	def release(self):
		"""Releases the stored texture."""
		self.texture.release()
	
	def read(self)->bytes:
		"""Reads the ModernGL texture.

		:return: Pixel data :class:`bytes`.
		:rtype: :class:`bytes`"""
		return self.texture.read()

	def get_size(self)->tuple[int,int]:
		"""Stored texture size property getter.

		:return: Texture size :class:`tuple`.
		:rtype: :class:`tuple`"""
		return tuple(self.texture.size)
	
	size = property(get_size)
	"""Texture size :class:`tuple` property."""

class HydraData(object):
	"""Global data object. Stores all ModernGL resources, including the context."""

	def __init__(self):
		"""Constructor method."""

		self.context: mgl.Context = None
		"""Addon's ModernGL context. Attached to Blender's OpenGL context."""

		self.maps: dict[str, Heightmap] = {}
		"""Heightmap dictionary. Uses UUID strings as keys."""

		self.programs: dict[str, mgl.Program] = {}
		"""Compiled ModernGL program list."""

		self.shaders: dict[str, mgl.ComputeShader] = {}
		"""Compiled ModernGL compute shader list."""
		
		self.lastPreview: str | None = None
		"""Name of last previewed object."""

		self._info_: list[str] = []
		"""Info message list."""
		self._error_: list[str] = []
		"""Error message list."""
	
	def init_context(self):
		"""Creates and saves the attached ModernGL :attr:`context`."""
		self.context = mgl.create_context()	#standalone crashes blender

	def has_map(self, id: str | None)->bool:
		"""Checks if map exists.

		:return: `True` if map exists in the :attr:`maps` list. `False` otherwise.
		:rtype: :class:`bool`"""
		return id in self.maps

	def try_release_map(self, id: str | None):
		"""Release specified map. Does nothing on invalid `id`.

		:param id: Map ID.
		:type id: :class:`str` or :class:`None`"""
		if id in self.maps:
			self.maps[id].release()
			del self.maps[id]
	
	def create_map(self, name: str, txt: mgl.Texture)->str:
		"""Creates and adds a heightmap into maps. Returns map ID.

		:param name: Name of created map.
		:type name: :class:`str`
		:param txt: Texture to be added.
		:type txt: :class:`moderngl.Texture`
		:return: New map UUID string.
		:rtype: :class:`str`"""
		id = str(uuid.uuid4())
		self.maps[id] = Heightmap(name, txt)
		return id
	
	def report(self, caller, callerName:str="Hydra"):
		"""Shows either stored error or info messages and clears them.

		:param caller: `Operation` calling this function.
		:param callerName: Message box title.
		:type callerName: :class:`str`"""
		if len(self._error_) != 0:
			show_message(" ".join(self._error_), title=callerName, icon="ERROR")
		if len(self._info_) != 0:
			caller.report({"INFO"}, " ".join(self._info_))

		self._info_ = []
		self._error_ = []
	
	def free_all(self):
		"""Frees all allocated maps."""
		for i in self.maps.values():
			i.release()
		self.maps = {}

	def add_message(self, message: str, error: bool=False):
		"""Adds an info message.

		:param message: Message to be added.
		:type message: :class:`str`"""
		if error:
			self._error_.append(message)
		else:
			self._info_.append(message)

#-------------------------------------------- Extra

def show_message(message: str, title:str="Hydra", icon:str='INFO'):
	"""Displays a message as popup.

	:param message: Message to be shown.
	:type message: :class:`str`
	:param title: Popup title.
	:type title: :class:`str`
	:param icon: Blender icon ID for the popup.
	:type icon: :class:`str`"""
	draw = lambda s,_: s.layout.label(text=message)
	bpy.context.window_manager.popup_menu(draw, title=title, icon=icon)

def get_preferences():
	"""Returns Hydra Blender preferences.

	:returns: Blender preferences for the Hydra addon."""
	return bpy.context.preferences.addons["Hydra"].preferences

_R_NUMBER: re.Pattern = re.compile(r"\d+$")
"""Ending number RegEx."""
def increment_layer(name: str, default: str)->str:
	"""Increments given layer name.

	:param name: Layer name to be incremented.
	:type name: :class:`str`
	:param default: Default layer name if incrementation fails.
	:type default: :class:`str`
	:returns: Incremented layer name."""
	if g := _R_NUMBER.search(name):
		num = str(int(g.group(0))+1)
		return _R_NUMBER.sub(num, default)
	else:
		return default

_R_OWNER: re.Pattern = re.compile(r"HYD_(.+?)_\w+$")
"""Hydra naming convention RegEx. Groups original owner name."""
def get_owner(name: str, previewName: str)->str | None:
	"""Gets the original object, which generated the given name.

	:param name: Name, which was generated by other object.
	:type name: :class:`str`
	:param previewName: Name for a corresponding preview object.
	:type previewName: :class:`str`
	:returns: Name of the original object. `None` if not found or if `name` is a preview.
	:rtype: :class:`str` or :class:`None`"""
	if name == previewName:
		return None
	if m := _R_OWNER.match(name):
		return m.group(1)
	return None

_SPACE_OBJECT = "VIEW_3D"
_SPACE_IMAGE = "IMAGE_EDITOR"

#-------------------------------------------- Vars

data: HydraData = HydraData()
"""Global data variable for the whole project."""